Algoritmo "exemploEnquanto"
// Disciplina   : [Lógica de Programação JS]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Kauan
// Data atual  : 27/03/2024
Var
// Seção de Declarações das variáveis 
 contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 enquanto contadora<8 faca
 escreval("Jailson")
           contadora<-contadora+1
 fimenquanto

Fimalgoritmo